const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=name=>fs.readFileSync(path.join(root,name),'utf8');
let app=read('index.html');
app=app.replace(/<link\b[^>]+>/g,'').replace('</head>',`<style>${read('site.css')}</style></head>`);
app=app.replace("const preview=new URLSearchParams(location.search).get('test')==='loading';","const preview=true;");
app=app.replace(/<script id="gameEngine"[\s\S]*?<\/script>/,()=>`<script>${read('game.js').replace(/\}\)\(\);\s*$/,()=>read('scripts/review-bridge.js')+'\n})();')}</script>`);
for(const name of ['audio.js','mobile.js'])app=app.replace(new RegExp('<script async src="\\./'+name.replace('.','\\.')+'[^>]*><\\/script>'),()=>`<script>${read(name)}</script>`);
app=app.replace('</body>',"<script>window.PoolStartup?.ready('styles');</script></body>");
const cache=new Map();
app=app.replace(/(?:\.\/)?(?:assets|sounds)\/[A-Za-z0-9_.-]+\.(?:jpg|png|webp|svg|mp3|m4a|wav)/g,rel=>{
 const name=rel.replace(/^\.\//,'');if(!cache.has(name)){
  const ext=path.extname(name),mime={'.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.mp3':'audio/mpeg','.m4a':'audio/mp4','.wav':'audio/wav'}[ext];cache.set(name,`data:${mime};base64,${fs.readFileSync(path.join(root,name)).toString('base64')}`);
 }return cache.get(name);
});
const pages=[['启航加载','火箭随加载进度抵达赛场。此页显示资源已准备就绪的状态。'],['欢迎入场','左侧邀请，右侧球台。新增全屏入口，进入页面即尝试播放入场音乐。'],['对战模式','冷光卡片与统一的科幻视觉。可选择人机、训练或双人同屏。'],['玩法选择','八球与九球分区清楚，保留易读文字与明确操作。'],['对手难度','大师仍以进攻为主，同时考虑白球落袋风险和下一杆位置。'],['对局球台','浅蓝台呢、细腻树脂反光、清晰球号与贴台阴影。可点击击球测试八球开球。'],['杆法与加塞','放大白球精细选择击球点，点下方勾号确认。'],['专项训练','四种可重复球位，方便比较力度、杆法、加塞和落袋反馈。'],['入袋试打','点右侧“击球”体验慢球入袋：观察加速下坠、袋沿遮挡与袋底落袋声。精调支持精细／均衡／灵活三档。'],['赛后结算','示例比分。可返回主页或再来一局，真实对局会自动填写结果。']];
const detailImages=process.argv.slice(3,5).map(file=>'data:image/png;base64,'+fs.readFileSync(file).toString('base64'));
const details=detailImages.length?`<dialog id="qualityEvidence"><button type="button" onclick="document.getElementById('qualityEvidence').close()">关闭</button><h2>真实材质与入袋细节</h2><p>以下图像由当前游戏引擎实际绘制。上图是浅蓝球桌，下图逐帧展示上、下中袋的自由落体和袋沿遮挡。</p>${detailImages.map(src=>`<img src="${src}" alt="游戏引擎绘制的材质与入袋效果">`).join('')}</dialog>`:'';
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>光域台球 · 浅蓝真实材质预览</title><style>
*{box-sizing:border-box}body{margin:0;background:#030810;color:#d9e8f3;font-family:system-ui,"PingFang SC",sans-serif;overflow:hidden}header{height:64px;padding:0 26px;border-bottom:1px solid #8accdf26;display:flex;align-items:center;gap:14px;background:#07121f}header strong{font-size:16px;letter-spacing:2px}header span{color:#84a0b4;font-size:11px;letter-spacing:2px}header b{margin-left:auto;color:#9be5f3;border:1px solid #6aa9bc55;padding:7px 12px;font-size:11px;border-radius:4px;font-weight:500}.viewport{position:relative;height:calc(100dvh - 148px);display:grid;place-items:center;padding:12px 18px;background:radial-gradient(ellipse at 50% 40%,#142236,#030810)}.screen{width:1400px;height:790px;position:absolute;transform-origin:center center;border:1px solid #7cb9d942;border-radius:10px;overflow:hidden;box-shadow:0 20px 70px #0008}iframe{display:block;width:1400px;height:790px;border:0;background:#060e1a}footer{height:84px;display:flex;align-items:center;gap:22px;padding:12px 26px;border-top:1px solid #8accdf26;background:#07111d}button,select{font:inherit;color:#c6f5ff;background:#123040;border:1px solid #679dbb70;border-radius:5px;padding:10px 15px;cursor:pointer}button:disabled{opacity:.35;cursor:default}button:hover{background:#20506a}.text{flex:1;min-width:0}.text strong{font-size:15px;letter-spacing:1px}.text p{color:#91a8bb;font-size:12px;margin:6px 0;line-height:1.5}#counter{font:12px monospace;color:#a4d4ea;margin-right:10px}select{font-size:11px;padding:7px 9px;max-width:150px}.nav{display:flex;gap:8px;align-items:center}.launch{color:#84a5b8;font-size:11px}.audio-note{margin-left:auto;font-size:11px;color:#8dabbf;letter-spacing:0}
@media(max-width:700px){header{height:48px;padding:0 12px;gap:8px}header strong{font-size:12px}header span,.audio-note{display:none}header b{font-size:9px}.viewport{height:calc(100dvh - 148px);padding:4px}footer{padding:9px 12px;height:100px;gap:10px}.text p{font-size:10px}.text strong{font-size:12px}.nav{gap:4px}button{font-size:11px;padding:9px}select{max-width:100px}#counter{display:none}}
dialog{max-width:1100px;width:92vw;max-height:90dvh;overflow:auto;background:#081625;color:#d9edf5;border:1px solid #7fc4dc66;border-radius:12px;padding:20px}dialog::backdrop{background:#01060be8}dialog img{display:block;width:100%;height:auto;margin:18px 0}dialog h2{font-size:20px}dialog p{font-size:13px;line-height:1.7;color:#a3bfcd}dialog>button{float:right}
</style><header><strong>光域台球</strong><span>REALISM / QUALITY REVIEW</span>${detailImages.length?`<button type="button" onclick="document.getElementById('qualityEvidence').showModal()">查看细节</button>`:''}<small class="audio-note">若浏览器拦截音乐，轻触游戏画面即可开启</small><b>未部署 · 交互审阅稿</b></header><main class="viewport"><div class="screen"><iframe id="reviewFrame" title="光域台球逐页交互预览" allow="autoplay; fullscreen" allowfullscreen></iframe></div></main><footer><div class="text"><strong id="pageTitle">正在准备预览…</strong><p id="pageNote">所有素材均已打包，无须连接游戏网站。</p></div><div class="nav"><span id="counter"></span><button id="prev" type="button">← 上一页</button><select id="jump" aria-label="选择预览页面"></select><button id="next" type="button">下一页 →</button></div></footer>${details}<script>
const pages=${JSON.stringify(pages)},frame=document.getElementById('reviewFrame'),jump=document.getElementById('jump');let current=5,ready=false;
for(let i=0;i<pages.length;i++){const option=document.createElement('option');option.value=i;option.textContent=String(i+1).padStart(2,'0')+' '+pages[i][0];jump.appendChild(option)}
function fit(){const box=document.querySelector('.viewport'),scale=Math.min((box.clientWidth-24)/1400,(box.clientHeight-16)/790);document.querySelector('.screen').style.transform='scale('+Math.max(.1,scale)+')'}
function show(index){current=Math.max(0,Math.min(pages.length-1,index));document.getElementById('pageTitle').textContent=pages[current][0];document.getElementById('pageNote').textContent=pages[current][1];document.getElementById('counter').textContent=String(current+1).padStart(2,'0')+' / '+pages.length;jump.value=current;document.getElementById('prev').disabled=current===0;document.getElementById('next').disabled=current===pages.length-1;if(ready)frame.contentWindow.postMessage({type:'pool-review-page',page:current},'*')}
document.getElementById('prev').onclick=()=>show(current-1);document.getElementById('next').onclick=()=>show(current+1);jump.onchange=()=>show(Number(jump.value));document.addEventListener('keydown',e=>{if(e.target.tagName==='SELECT')return;if(e.key==='ArrowRight')show(current+1);if(e.key==='ArrowLeft')show(current-1)});window.addEventListener('resize',fit);window.addEventListener('message',e=>{if(e.source===frame.contentWindow&&e.data?.type==='pool-review-ready'){ready=true;show(current)}});fit();show(current);frame.srcdoc=${JSON.stringify(app).replace(/<\//g,'<\\/')};
</script></html>`;
const dest=process.argv[2]||path.join(root,'../fuguang-orbit-review.html');fs.writeFileSync(dest,html);console.log(JSON.stringify({file:dest,bytes:Buffer.byteLength(html),pages:pages.length,embeddedAssets:cache.size}));
